# color pallet
color_bg=colour232
color_inactive=colour234
color_sub=colour236
color_key=colour241
color_text=colour255

# basics
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
set -g default-terminal "xterm-256color"
set-option -gw xterm-keys on
set -g mouse on
set -g set-clipboard on
set -g history-limit 20000
set -sg escape-time 0
set -g base-index 1

# status bar
set -g status on
set -g status-position top
set -g status-justify "left"
set -g status-left ""
set -g status-right "#{?pane_in_mode,#(tmux-scrollbar #{scroll_position} #{history_size} #{pane_height}),#{?pane_synchronized,(sync) ,}#h [#S]}"
set-option -g status-right-length 60
## color
set -g status-style "bg=$color_bg,fg=$color_key"

# basic key binds
bind p \
  if-shell -F '#{==:#{pane_index},1}' \
  'previous-window; run "tmux select-pane -t $(tmux list-panes | wc -l)"' \
  'select-pane -t :.-'
bind n \
  if-shell -F '#{==:#{pane_index},#{window_panes}}' \
  'next-window; select-pane -t 1' \
  'select-pane -t :.+'

bind -n C-Pageup \
  if-shell -F '#{==:#{pane_index},1}' \
  'previous-window; run "tmux select-pane -t $(tmux list-panes | wc -l)"' \
  'select-pane -t :.-'
bind -n C-Pagedown \
  if-shell -F '#{==:#{pane_index},#{window_panes}}' \
  'next-window; select-pane -t 1' \
  'select-pane -t :.+'

# window
bind -n C-t new-window -a -c "#{pane_current_path}"
bind -n C-w \
  kill-pane\; \
  select-layout -E
setw -g pane-base-index 1
setw -g window-status-style "bg=$color_sub"
setw -g window-status-format "     "
setw -g window-status-current-style "bg=$color_key"
setw -g window-status-current-format "     "

# pane
bind -n M-\\ \
  split-window -h -c "#{pane_current_path}"\; \
  select-layout -E
bind -n M-¥ \
  split-window -h -c "#{pane_current_path}"\; \
  select-layout -E
bind -n M-- \
  split-window -v -c "#{pane_current_path}"\; \
  select-layout -E
bind -n C-Up resize-pane -Z
set -g pane-border-style "fg=$color_key"
set -g pane-active-border-style "fg=$color_text"

set-hook -g window-layout-changed \
  'if-shell -F "#{==:#{window_panes},1}" \
  "set -g pane-border-status off" \
  "set -g pane-border-status top"'

set -g pane-border-format ""

# copy mode
setw -g mode-keys vi

bind-key -T copy-mode-vi C-Left send-keys -X previous-word
bind-key -T copy-mode-vi C-Right send-keys -X next-word-end

bind-key -T copy-mode-vi u send-keys -X page-up
bind-key -T copy-mode-vi d send-keys -X page-down

bind-key -T copy-mode-vi S-Up \
  if-shell -F "#{selection_present}" \
  "send-keys -X cursor-up"\
  "send-keys -X begin-selection \; send-keys -X cursor-up"
bind-key -T copy-mode-vi S-Down \
  if-shell -F "#{selection_present}" \
  "send-keys -X cursor-down" \
  "send-keys -X begin-selection \; send-keys -X cursor-down"
bind-key -T copy-mode-vi S-Left \
  if-shell -F "#{selection_present}" \
  "send-keys -X cursor-left" \
  "send-keys -X begin-selection \; send-keys -X cursor-left"
bind-key -T copy-mode-vi S-Right \
  if-shell -F "#{selection_present}" \
  "send-keys -X cursor-right" \
  "send-keys -X begin-selection \; send-keys -X cursor-right"
bind-key -T copy-mode-vi C-c send-keys -X copy-pipe-and-cancel "cbcopy"

# sync mode
bind -T root F11 \
  if-shell -F '#{==:#{pane_synchronized},1}' \
  'set-window-option synchronize-panes off; refresh-client -S' \
  'set-window-option synchronize-panes on; refresh-client -S'

# off mode
bind -T root F12 \
  set prefix None\; \
  set key-table off\; \
  set status-style "fg=$color_sub"\; \
  setw -g window-status-style "bg=$color_inactive"\; \
  setw window-status-current-style "bg=$color_sub"\; \
  refresh-client -S
bind -T off F12 \
  set -u prefix\; \
  set -u key-table\; \
  set -u status-style\; \
  setw -g window-status-style "bg=$color_sub"\; \
  setw -u window-status-current-style\; \
  refresh-client -S
